import type { JobStage } from '../constants/stages';

export type JobPriority = 'High' | 'Medium' | 'Low';

export type TaskStatus = 'pending' | 'scheduled' | 'completed';

export type TaskCategory = 'Outreach' | 'Preparation' | 'Follow-up' | 'Research';

export interface JobLead {
  id: string;
  company: string;
  role: string;
  location: string;
  link: string;
  priority: JobPriority;
  stage: JobStage;
  lastTouchpoint: string;
  followUpDate?: string;
  automationScore: number;
  tags: string[];
  notes: string[];
}

export interface JobTask {
  id: string;
  jobId: string;
  title: string;
  category: TaskCategory;
  dueDate: string;
  status: TaskStatus;
  autoGenerated: boolean;
}

export type JobTaskWithLead = JobTask & {
  job?: JobLead;
};

export interface OutreachTemplate {
  id: string;
  title: string;
  purpose: string;
  prompt: string;
  followUpDays: number;
}

export interface JobFilters {
  search: string;
  stage: string;
  priority: string;
}

export interface NewJobFormState {
  company: string;
  role: string;
  location: string;
  link: string;
  priority: JobPriority;
  tags: string;
}
